name: Convert RBXLX to RBXL

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Lune
      run: |
        curl -L -o lune.zip https://github.com/lune-org/lune/releases/download/v0.10.5/lune-0.10.5-linux-amd64.zip
        unzip lune.zip
        chmod +x lune
        
    - name: Run Conversion
      run: ./lune run convert.luau
      
    - name: Upload Converted File
      uses: actions/upload-artifact@v4
      with:
        name: converted-place
        path: "*.rbxl"
        
